### PR TITLE
fetching supported themes from jsonresume.org/themes.json

### PR DESCRIPTION
**Pull request by mrancourt**
Loading the full list of supported themes directly from the JSON Resume themes registry.

Ref: #2

### CODE REVIEW

**Comment by mattberther** [comment]
@mrancourt happy to merge this as is - unless you were planning on adding the prompting for the theme name to this PR. thoughts?

**Comment by mrancourt** [comment]
@mattberther Great! for the prompting, I guess I could add it in another PR as I haven't worked on it yet.

**Comment by mattberther** [comment]
Thanks for the contribution @mrancourt. I appreciate it.

**Comment by mrancourt** [comment]
You're welcome @mattberther, glad I could help contributing.

**Pull request merged**
